// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/v1/machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeout       *int32                 `protobuf:"varint,1,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineCreateRequest) Reset() {
	*x = MachineCreateRequest{}
	mi := &file_proto_v1_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateRequest) ProtoMessage() {}

func (x *MachineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateRequest.ProtoReflect.Descriptor instead.
func (*MachineCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineCreateRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *MachineCreateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineCreateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MachineCreateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type MachineCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineCreateReply) Reset() {
	*x = MachineCreateReply{}
	mi := &file_proto_v1_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateReply) ProtoMessage() {}

func (x *MachineCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateReply.ProtoReflect.Descriptor instead.
func (*MachineCreateReply) Descriptor() ([]byte, []int) {
	return file_proto_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineCreateReply) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type MachineTerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineTerminateRequest) Reset() {
	*x = MachineTerminateRequest{}
	mi := &file_proto_v1_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineTerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineTerminateRequest) ProtoMessage() {}

func (x *MachineTerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineTerminateRequest.ProtoReflect.Descriptor instead.
func (*MachineTerminateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineTerminateRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

var File_proto_v1_machine_proto protoreflect.FileDescriptor

const file_proto_v1_machine_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/machine.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x02\n" +
	"\x14MachineCreateRequest\x12\x1d\n" +
	"\atimeout\x18\x01 \x01(\x05H\x00R\atimeout\x88\x01\x01\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.v1.MachineCreateRequest.MetadataEntryR\bmetadata\x123\n" +
	"\x03env\x18\x03 \x03(\v2!.v1.MachineCreateRequest.EnvEntryR\x03env\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_timeoutB\a\n" +
	"\x05_name\"3\n" +
	"\x12MachineCreateReply\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"8\n" +
	"\x17MachineTerminateRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId2\x87\x01\n" +
	"\aMachine\x12:\n" +
	"\x06Create\x12\x18.v1.MachineCreateRequest\x1a\x16.v1.MachineCreateReply\x12@\n" +
	"\tTerminate\x12\x1b.v1.MachineTerminateRequest\x1a\x16.google.protobuf.EmptyB3Z1github.com/remicaumette/code-sandbox/pkg/proto/v1b\x06proto3"

var (
	file_proto_v1_machine_proto_rawDescOnce sync.Once
	file_proto_v1_machine_proto_rawDescData []byte
)

func file_proto_v1_machine_proto_rawDescGZIP() []byte {
	file_proto_v1_machine_proto_rawDescOnce.Do(func() {
		file_proto_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_machine_proto_rawDesc), len(file_proto_v1_machine_proto_rawDesc)))
	})
	return file_proto_v1_machine_proto_rawDescData
}

var file_proto_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_machine_proto_goTypes = []any{
	(*MachineCreateRequest)(nil),    // 0: v1.MachineCreateRequest
	(*MachineCreateReply)(nil),      // 1: v1.MachineCreateReply
	(*MachineTerminateRequest)(nil), // 2: v1.MachineTerminateRequest
	nil,                             // 3: v1.MachineCreateRequest.MetadataEntry
	nil,                             // 4: v1.MachineCreateRequest.EnvEntry
	(*emptypb.Empty)(nil),           // 5: google.protobuf.Empty
}
var file_proto_v1_machine_proto_depIdxs = []int32{
	3, // 0: v1.MachineCreateRequest.metadata:type_name -> v1.MachineCreateRequest.MetadataEntry
	4, // 1: v1.MachineCreateRequest.env:type_name -> v1.MachineCreateRequest.EnvEntry
	0, // 2: v1.Machine.Create:input_type -> v1.MachineCreateRequest
	2, // 3: v1.Machine.Terminate:input_type -> v1.MachineTerminateRequest
	1, // 4: v1.Machine.Create:output_type -> v1.MachineCreateReply
	5, // 5: v1.Machine.Terminate:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_machine_proto_init() }
func file_proto_v1_machine_proto_init() {
	if File_proto_v1_machine_proto != nil {
		return
	}
	file_proto_v1_machine_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_machine_proto_rawDesc), len(file_proto_v1_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_machine_proto_goTypes,
		DependencyIndexes: file_proto_v1_machine_proto_depIdxs,
		MessageInfos:      file_proto_v1_machine_proto_msgTypes,
	}.Build()
	File_proto_v1_machine_proto = out.File
	file_proto_v1_machine_proto_goTypes = nil
	file_proto_v1_machine_proto_depIdxs = nil
}
