// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/v1/node_registry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRegistryRegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Authorization   string                 `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	PublicIpAddress string                 `protobuf:"bytes,2,opt,name=public_ip_address,json=publicIpAddress,proto3" json:"public_ip_address,omitempty"`
	VCpus           int32                  `protobuf:"varint,3,opt,name=v_cpus,json=vCpus,proto3" json:"v_cpus,omitempty"`
	Memory          int64                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	ServerEndpoint  string                 `protobuf:"bytes,5,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeRegistryRegisterRequest) Reset() {
	*x = NodeRegistryRegisterRequest{}
	mi := &file_proto_v1_node_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistryRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistryRegisterRequest) ProtoMessage() {}

func (x *NodeRegistryRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistryRegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeRegistryRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_registry_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRegistryRegisterRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *NodeRegistryRegisterRequest) GetPublicIpAddress() string {
	if x != nil {
		return x.PublicIpAddress
	}
	return ""
}

func (x *NodeRegistryRegisterRequest) GetVCpus() int32 {
	if x != nil {
		return x.VCpus
	}
	return 0
}

func (x *NodeRegistryRegisterRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *NodeRegistryRegisterRequest) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

type NodeRegistryRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistryRegisterReply) Reset() {
	*x = NodeRegistryRegisterReply{}
	mi := &file_proto_v1_node_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistryRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistryRegisterReply) ProtoMessage() {}

func (x *NodeRegistryRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_node_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistryRegisterReply.ProtoReflect.Descriptor instead.
func (*NodeRegistryRegisterReply) Descriptor() ([]byte, []int) {
	return file_proto_v1_node_registry_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRegistryRegisterReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_proto_v1_node_registry_proto protoreflect.FileDescriptor

const file_proto_v1_node_registry_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/node_registry.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\"\xc7\x01\n" +
	"\x1bNodeRegistryRegisterRequest\x12$\n" +
	"\rauthorization\x18\x01 \x01(\tR\rauthorization\x12*\n" +
	"\x11public_ip_address\x18\x02 \x01(\tR\x0fpublicIpAddress\x12\x15\n" +
	"\x06v_cpus\x18\x03 \x01(\x05R\x05vCpus\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x03R\x06memory\x12'\n" +
	"\x0fserver_endpoint\x18\x05 \x01(\tR\x0eserverEndpoint\"4\n" +
	"\x19NodeRegistryRegisterReply\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2c\n" +
	"\x13NodeRegistryService\x12L\n" +
	"\bRegister\x12\x1f.v1.NodeRegistryRegisterRequest\x1a\x1d.v1.NodeRegistryRegisterReply0\x01B3Z1github.com/remicaumette/code-sandbox/pkg/proto/v1b\x06proto3"

var (
	file_proto_v1_node_registry_proto_rawDescOnce sync.Once
	file_proto_v1_node_registry_proto_rawDescData []byte
)

func file_proto_v1_node_registry_proto_rawDescGZIP() []byte {
	file_proto_v1_node_registry_proto_rawDescOnce.Do(func() {
		file_proto_v1_node_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_node_registry_proto_rawDesc), len(file_proto_v1_node_registry_proto_rawDesc)))
	})
	return file_proto_v1_node_registry_proto_rawDescData
}

var file_proto_v1_node_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_node_registry_proto_goTypes = []any{
	(*NodeRegistryRegisterRequest)(nil), // 0: v1.NodeRegistryRegisterRequest
	(*NodeRegistryRegisterReply)(nil),   // 1: v1.NodeRegistryRegisterReply
}
var file_proto_v1_node_registry_proto_depIdxs = []int32{
	0, // 0: v1.NodeRegistryService.Register:input_type -> v1.NodeRegistryRegisterRequest
	1, // 1: v1.NodeRegistryService.Register:output_type -> v1.NodeRegistryRegisterReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_node_registry_proto_init() }
func file_proto_v1_node_registry_proto_init() {
	if File_proto_v1_node_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_node_registry_proto_rawDesc), len(file_proto_v1_node_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_node_registry_proto_goTypes,
		DependencyIndexes: file_proto_v1_node_registry_proto_depIdxs,
		MessageInfos:      file_proto_v1_node_registry_proto_msgTypes,
	}.Build()
	File_proto_v1_node_registry_proto = out.File
	file_proto_v1_node_registry_proto_goTypes = nil
	file_proto_v1_node_registry_proto_depIdxs = nil
}
