#!/bin/bash
set -e

INIT_BIN="bin/baepo-initd"
WORKING_DIR="/tmp/build-initfs"
CWD=`pwd`
INITRAMFS="initramfs.cpio.gz"

rm -rf $WORKING_DIR

echo "Compiling the init program..."
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $INIT_BIN -ldflags "-s -w" cmd/baepo-initd/main.go
chmod +x $INIT_BIN

echo "Creating initramfs directory structure..."
mkdir -p $WORKING_DIR/{bin,dev,etc,proc,sys,tmp,run,sbin,mnt}

echo "Adding init to the filesystem..."
cp $INIT_BIN $WORKING_DIR/sbin/init

echo "Creating initramfs..."
(
    cd "$WORKING_DIR"
    find . -print0 | cpio --null -ov --format=newc | gzip -9 > "$CWD/resources/$INITRAMFS"
)

echo "Done! Created $INITRAMFS"
